remote_theme: pages-themes/minimal
title: Monica Lefton
description: Communicator | Writer | Reader

# Some themes use this for navigation:
nav_links:
  - title: About
    url: /
  - title: Work
    url: /work
  - title: Intermission
    url: /intermission